services:
  - type: web
    name: bitgetbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSPHRASE
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: BOT_PASSWORD
        sync: false
      - key: PORT
        value: "10000"
