import os

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
BITGET_API_KEY = os.environ.get("BITGET_API_KEY", "")
BITGET_API_SECRET = os.environ.get("BITGET_API_SECRET", "")
BITGET_API_PASSPHRASE = os.environ.get("BITGET_API_PASSPHRASE", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_USERNAME = os.environ.get("GITHUB_USERNAME", "")
GITHUB_REPO = "bitgetbot"

BOT_PASSWORD = "OLLOBERGAN"

FUTURES_BASE_URL = "https://api.bitget.com"
SPOT_BASE_URL = "https://api.bitget.com"

FUTURES_PRODUCT_TYPE = "USDT-FUTURES"
FUTURES_MARGIN_COIN = "USDT"
MARGIN_MODE = "crossed"

BALANCE_USE_RATIO = 0.50
ORDER_RATIO = 0.05
MAX_FUTURES_ORDERS = 10
MAX_SPOT_ORDERS = 20
MIN_ORDER_USDT = 1.0
MAX_ORDER_USDT = 5.0

AUTO_TRADE_CONFIDENCE = 70        # 70%+ → avtomatik savdo, signal yuboriladi
SIGNAL_NOTIFY_THRESHOLD = 70      # foydalanuvchiga signal yuboriladigan minimum
MIN_SIGNAL_CONFIDENCE = 55        # tahlil uchun minimum (tarixi saqlanadi)
ASK_PERMISSION_CONFIDENCE_MIN = 0 # o'chirildi — faqat 70%+ auto
ASK_PERMISSION_CONFIDENCE_MAX = 0

SIGNAL_CHECK_INTERVAL = 300
PRICE_UPDATE_INTERVAL = 60

TP_COUNT = 2
SL_COUNT = 1

SHORT_TRADE_HOURS_MIN = 1
SHORT_TRADE_HOURS_MAX = 48

TOP_SYMBOLS_COUNT = 10
SCAN_TOP_N = 30
